# Generated by Django 3.2.9 on 2023-08-18 12:47

import core.utils.file
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('duration', models.DurationField(blank=True, max_length=255, null=True, verbose_name='Длительность')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст произведения')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.utils.file.get_song_filepath, verbose_name='Файл')),
                ('analysis', models.FileField(blank=True, null=True, upload_to=core.utils.file.get_analysis_filepath, verbose_name='Разбор')),
                ('about', models.FileField(blank=True, null=True, upload_to=core.utils.file.get_about_filepath, verbose_name='Рассказ об авторе')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='core.author', verbose_name='Автор')),
                ('singer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.singer', verbose_name='Исполнитель')),
            ],
        ),
    ]
