# Generated by Django 4.2.7 on 2024-05-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Фамилия'),
        ),
    ]
