# Generated by Django 3.2.9 on 2023-08-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='ссылка'),
        ),
    ]
