# Generated by Django 4.2.7 on 2024-05-15 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_author_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='creation_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.author', verbose_name='Автор произведения'),
        ),
    ]
