# Generated by Django 3.2.9 on 2023-08-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='slug',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='ссылка'),
        ),
    ]
