# Generated by Django 3.2.9 on 2023-09-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_song_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='type',
            field=models.CharField(choices=[['music', 'Музыкант'], ['artist', 'Художник'], ['philosopher', 'Философ']], max_length=255, null=True, unique=True, verbose_name='тип'),
        ),
    ]
