# Generated by Django 4.2.7 on 2024-05-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_author_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
                ('message', models.TextField(verbose_name='Название')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания сообщения')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
