# Generated by Django 4.2.7 on 2024-05-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_film',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
