# Generated by Django 4.2.7 on 2024-07-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_song_youtube_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Раздел выключен'),
        ),
    ]
