# Generated by Django 4.2.7 on 2024-09-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Раздел заблокирован'),
        ),
    ]
