# Generated by Django 4.2.7 on 2024-09-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_genre_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='is_disabled',
            field=models.BooleanField(default=False, verbose_name='Раздел выключен'),
        ),
    ]
