# Generated by Django 4.2.7 on 2024-09-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_genre_is_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=255, null=True, unique=True, verbose_name='ссылка')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Суперкатегория',
                'verbose_name_plural': 'Суперкатегории',
                'ordering': ['name'],
            },
        ),
    ]
