# Generated by Django 4.2.7 on 2024-09-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_supercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='supercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.supercategory', verbose_name='Суперкатегория'),
        ),
    ]
