# Generated by Django 3.2.9 on 2023-09-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_author_century'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='teacher',
            field=models.ManyToManyField(related_name='_core_author_teacher_+', to='core.Author'),
        ),
    ]
