# Generated by Django 4.2.7 on 2024-09-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_category_supercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supercategory_images'),
        ),
    ]
