# Generated by Django 3.2.9 on 2023-09-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_author_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='antagonist',
            field=models.ManyToManyField(related_name='_core_author_antagonist_+', to='core.Author'),
        ),
        migrations.AddField(
            model_name='author',
            name='associate',
            field=models.ManyToManyField(related_name='_core_author_associate_+', to='core.Author'),
        ),
    ]
