# Generated by Django 3.2.9 on 2023-09-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230927_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='antagonist',
            field=models.ManyToManyField(blank=True, null=True, related_name='_core_author_antagonist_+', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='associate',
            field=models.ManyToManyField(blank=True, null=True, related_name='_core_author_associate_+', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='_core_author_teacher_+', to='core.Author'),
        ),
    ]
