# Generated by Django 4.2.7 on 2024-09-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_supercategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercategory',
            name='description',
            field=models.CharField(default=0, max_length=500, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
