# Generated by Django 3.2.9 on 2023-09-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230927_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='_core_author_student_+', to='core.Author'),
        ),
    ]
