# Generated by Django 4.2.7 on 2024-10-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_supercategory_is_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое название'),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(choices=[['music', 'Музыкант'], ['writer', 'Литератор, Литературное произведение'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['lector', 'Лектор'], ['director', 'Режиссер'], ['spiritual', 'Духоносная персона']], max_length=255, null=True, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(choices=[['music', 'Музыкант'], ['writer', 'Литератор, Литературное произведение'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['lector', 'Лектор'], ['director', 'Режиссер'], ['spiritual', 'Духоносная персона']], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='centurydescription',
            name='type',
            field=models.CharField(blank=True, choices=[['music', 'Музыкант'], ['writer', 'Литератор, Литературное произведение'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['lector', 'Лектор'], ['director', 'Режиссер'], ['spiritual', 'Духоносная персона']], max_length=100, null=True, verbose_name='тип жанра'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='type',
            field=models.CharField(blank=True, choices=[['music', 'Музыкант'], ['writer', 'Литератор, Литературное произведение'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['lector', 'Лектор'], ['director', 'Режиссер'], ['spiritual', 'Духоносная персона']], max_length=100, null=True, verbose_name='тип жанра'),
        ),
    ]
