# Generated by Django 3.2.9 on 2023-10-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=255, null=True, unique=True, verbose_name='ссылка')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='antagonist',
            field=models.ManyToManyField(blank=True, related_name='_core_author_antagonist_+', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='associate',
            field=models.ManyToManyField(blank=True, related_name='_core_author_associate_+', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='_core_author_student_+', to='core.Author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='_core_author_teacher_+', to='core.Author'),
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.CharField(max_length=255, null=True, unique=True, verbose_name='ссылка')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.author')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to='core.author')),
                ('genre', models.ManyToManyField(blank=True, related_name='films', to='core.Genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
