# Generated by Django 3.2.9 on 2023-10-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20231006_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='film',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='film',
            name='author',
        ),
    ]
