# Generated by Django 3.2.9 on 2023-10-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20231009_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='text_preview',
            field=models.CharField(default=0, max_length=255, verbose_name='текст_превью'),
            preserve_default=False,
        ),
    ]
