# Generated by Django 3.2.9 on 2023-10-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_author_text_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='text_preview',
            field=models.CharField(max_length=755, verbose_name='текст_превью'),
        ),
    ]
