# Generated by Django 3.2.9 on 2023-10-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20231018_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='text_preview',
            field=models.CharField(max_length=1555, verbose_name='текст_превью'),
        ),
    ]
