# Generated by Django 3.2.9 on 2023-10-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_author_text_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='text_preview',
            field=models.CharField(max_length=2555, verbose_name='текст_превью'),
        ),
    ]
