# Generated by Django 3.2.9 on 2023-10-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_author_text_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
