# Generated by Django 3.2.9 on 2023-10-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='text_preview',
            field=models.CharField(max_length=1000, verbose_name='текст_превью'),
        ),
    ]
