# Generated by Django 3.2.9 on 2023-10-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_author_text_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='text_preview',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='текст_превью'),
        ),
    ]
