# Generated by Django 3.2.9 on 2023-10-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_author_text_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='text',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='текст_превью'),
        ),
    ]
