# Generated by Django 3.2.9 on 2023-10-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_author_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='text',
            field=models.TextField(blank=True, max_length=40000, null=True, verbose_name='текст'),
        ),
    ]
