# Generated by Django 3.2.9 on 2023-10-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_author_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='preview_text',
        ),
        migrations.AlterField(
            model_name='author',
            name='century',
            field=models.IntegerField(blank=True, choices=[[-5, '5 до н.э.'], [-4, '4 до н.э.'], [-3, '3 до н.э.'], [-2, '2 до н.э.'], [-1, '1 до н.э.'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10'], [11, '11'], [12, '12'], [13, '13'], [14, '14'], [15, '15'], [16, '16'], [17, '17'], [18, '18'], [19, '19'], [20, '20'], [21, '21']], null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(choices=[['music', 'Музыкант'], ['writer', 'Литератор'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['musician', 'Музыкант'], ['director', 'Режиссер']], max_length=255, null=True, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(choices=[['music', 'Музыкант'], ['writer', 'Литератор'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['musician', 'Музыкант'], ['director', 'Режиссер']], max_length=300, null=True),
        ),
    ]
