# Generated by Django 3.2.9 on 2023-10-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_author_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='about_text',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='about'),
        ),
    ]
