# Generated by Django 3.2.9 on 2023-10-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_category_about_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='preview_text',
        ),
        migrations.AlterField(
            model_name='category',
            name='about_text',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='about'),
        ),
    ]
