# Generated by Django 3.2.9 on 2023-10-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_genre_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(choices=[['music', 'Музыкант'], ['writer', 'Литератор'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['musician', 'Музыкант'], ['lector', 'Лектор'], ['director', 'Режиссер'], ['spiritual', 'Духоносный']], max_length=255, null=True, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(choices=[['music', 'Музыкант'], ['writer', 'Литератор'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['musician', 'Музыкант'], ['lector', 'Лектор'], ['director', 'Режиссер'], ['spiritual', 'Духоносный']], max_length=300, null=True),
        ),
    ]
