# Generated by Django 4.2.7 on 2023-11-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_singer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='antagonist',
            field=models.ManyToManyField(blank=True, related_name='antagonist', to='core.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='associate',
            field=models.ManyToManyField(blank=True, related_name='associate', to='core.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='century',
            field=models.IntegerField(blank=True, choices=[[-1, '1 до н.э.'], [1, '1'], [2, '2'], [3, '3'], [4, '4'], [5, '5'], [6, '6'], [7, '7'], [8, '8'], [9, '9'], [10, '10'], [11, '11'], [12, '12'], [13, '13'], [14, '14'], [15, '15'], [16, '16'], [17, '17'], [18, '18'], [19, '19'], [20, '20'], [21, '21']], null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student', to='core.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='students', to='core.author'),
        ),
    ]
