# Generated by Django 4.2.7 on 2023-11-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_film_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='silver_century',
            field=models.BooleanField(default=False, max_length=1, verbose_name='серебряный век'),
        ),
    ]
