# Generated by Django 4.2.7 on 2023-11-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_author_silver_century'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='silver_century',
        ),
        migrations.AddField(
            model_name='author',
            name='century_type',
            field=models.CharField(blank=True, choices=[['silver', 'Серебряный'], ['gold', 'Золотой']], max_length=255, null=True, verbose_name='группа'),
        ),
    ]
