# Generated by Django 4.2.7 on 2023-11-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_author_silver_century_author_century_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Century',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, help_text='значение', unique=True, verbose_name='Век')),
                ('display_name', models.CharField(help_text='отображаемое значение', max_length=255, verbose_name='Век')),
                ('slug', models.CharField(max_length=255, null=True, unique=True, verbose_name='ссылка')),
            ],
            options={
                'verbose_name_plural': 'века',
                'ordering': ['value'],
            },
        ),
        migrations.RemoveField(
            model_name='author',
            name='century',
        ),
        migrations.RemoveField(
            model_name='author',
            name='century_type',
        ),
    ]
