# Generated by Django 4.2.7 on 2023-12-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_author_century'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='год рождения'),
        ),
        migrations.AddField(
            model_name='century',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='описание века'),
        ),
    ]
