# Generated by Django 4.2.7 on 2023-12-04 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_author_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authors', to='core.category'),
        ),
    ]
