# Generated by Django 4.2.7 on 2023-12-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='antagonist',
            field=models.ManyToManyField(blank=True, to='core.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='associate',
            field=models.ManyToManyField(blank=True, to='core.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='student',
            field=models.ManyToManyField(blank=True, to='core.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='core.author'),
        ),
    ]
