# Generated by Django 4.2.7 on 2023-12-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_author_antagonist_alter_author_associate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=255, null=True, unique=True, verbose_name='ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
