# Generated by Django 4.2.7 on 2023-12-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='category',
        ),
        migrations.AddField(
            model_name='author',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='authors', to='core.subcategory'),
        ),
    ]
