# Generated by Django 4.2.7 on 2024-01-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_category_parent_alter_subcategory_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilGenre',
        ),
        migrations.RemoveField(
            model_name='author',
            name='website',
        ),
        migrations.AddField(
            model_name='author',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='core.category'),
        ),
    ]
