# Generated by Django 4.2.7 on 2024-01-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_delete_filgenre_remove_author_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenturyDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='описание века')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category')),
                ('century', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.century')),
            ],
        ),
    ]
