# Generated by Django 4.2.7 on 2024-01-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_centurydescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='centurydescription',
            name='detailed_text',
            field=models.TextField(blank=True, null=True, verbose_name='детальное описание'),
        ),
    ]
