# Generated by Django 4.2.7 on 2024-01-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_centurydescription_mistake_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centurydescription',
            name='mistake_text',
            field=models.TextField(blank=True, null=True, verbose_name='описание ошибок'),
        ),
    ]
