# Generated by Django 4.2.7 on 2024-01-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_centurydescription_mistake_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='centurydescription',
            name='Rel_changes_text',
            field=models.TextField(blank=True, null=True, verbose_name='религиозные изменения'),
        ),
    ]
