# Generated by Django 4.2.7 on 2024-02-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_centurydescription_rel_changes_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centurydescription',
            old_name='Rel_changes_text',
            new_name='rel_changes_text',
        ),
        migrations.AddField(
            model_name='genre',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='тип жанра'),
        ),
    ]
