# Generated by Django 4.2.7 on 2024-02-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_genre_text_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='authors', to='core.genre'),
        ),
    ]
