# Generated by Django 4.2.7 on 2024-02-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_author_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='about_text',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='about'),
        ),
    ]
