# Generated by Django 4.2.7 on 2024-02-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_subcategory_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.genre'),
        ),
    ]
