# Generated by Django 4.2.7 on 2024-02-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_genre_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='type',
            field=models.CharField(blank=True, choices=[['music', 'Музыкант'], ['writer', 'Литератор'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['musician', 'Музыкант'], ['lector', 'Лектор'], ['director', 'Режиссер'], ['spiritual', 'Духоносный']], max_length=100, null=True, verbose_name='тип жанра'),
        ),
    ]
