# Generated by Django 4.2.7 on 2024-02-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_genre_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(choices=[['music', 'Музыкант'], ['writer', 'Литератор'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['lector', 'Лектор'], ['director', 'Режиссер'], ['spiritual', 'Духоносный']], max_length=255, null=True, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(choices=[['music', 'Музыкант'], ['writer', 'Литератор'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['lector', 'Лектор'], ['director', 'Режиссер'], ['spiritual', 'Духоносный']], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='type',
            field=models.CharField(blank=True, choices=[['music', 'Музыкант'], ['writer', 'Литератор'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['lector', 'Лектор'], ['director', 'Режиссер'], ['spiritual', 'Духоносный']], max_length=100, null=True, verbose_name='тип жанра'),
        ),
    ]
