# Generated by Django 4.2.7 on 2024-02-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_author_type_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='text_preview',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='текст_превью'),
        ),
    ]
