# Generated by Django 4.2.7 on 2024-02-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_genre_text_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
