# Generated by Django 4.2.7 on 2024-02-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_category_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='website',
        ),
        migrations.AddField(
            model_name='genre',
            name='website',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
