# Generated by Django 4.2.7 on 2024-03-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_remove_category_website_genre_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='type',
            field=models.CharField(choices=[('youtube', 'youtube'), ('internal', 'закаченный файл')], default='youtube', max_length=255, verbose_name='тип'),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
