# Generated by Django 4.2.7 on 2024-03-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_song_type_song_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
