# Generated by Django 4.2.7 on 2024-04-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_genre_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='centurydescription',
            name='type',
            field=models.CharField(blank=True, choices=[['music', 'Музыкант'], ['writer', 'Литератор'], ['artist', 'Художник'], ['philosopher', 'Философ'], ['lector', 'Лектор'], ['director', 'Режиссер'], ['spiritual', 'Духоносный']], max_length=100, null=True, verbose_name='тип жанра'),
        ),
    ]
