# Generated by Django 4.2.7 on 2024-04-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_category_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug2',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='ссылка'),
        ),
    ]
