# Generated by Django 4.2.7 on 2024-04-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_author_slug2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ссылка'),
        ),
    ]
