from .author import Author
from .singer import Singer
from .song import Song
#from .song import Film
from .category import Category
from .genre import Genre
from .film import Film
from .picture import Picture
from .century import Century
from .video import Video
